# Generated by Django 5.1.3 on 2026-04-26 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('sessions_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('attended', 'Attended'), ('no_show', 'No-show')], default='confirmed', max_length=12)),
                ('channel', models.CharField(choices=[('subscription', 'Covered by subscription'), ('unit', 'Pay-per-class')], max_length=15)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='sessions_app.coursesession')),
                ('payment', models.ForeignKey(blank=True, help_text='Set for channel=unit; null for subscription-covered bookings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='payments.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='bookings_bo_user_id_69a5d5_idx'), models.Index(fields=['course_session', 'status'], name='bookings_bo_course__ba999a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'confirmed')), fields=('user', 'course_session'), name='unique_confirmed_booking_per_user_session')],
            },
        ),
    ]
