# Generated by Django 5.1.3 on 2026-04-28 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('sub_activated', 'Subscription activated'), ('sub_cancelled', 'Subscription cancelled'), ('pay_succeeded', 'Payment succeeded'), ('pay_failed', 'Payment failed'), ('book_created', 'Booking created'), ('book_cancelled', 'Booking cancelled'), ('admin_user_toggled', 'Admin: user toggled'), ('admin_user_role_changed', 'Admin: role changed')], max_length=40)),
                ('target_type', models.CharField(blank=True, help_text="App-qualified model name, e.g. 'subscriptions.Subscription'.", max_length=80)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action; null for system events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', '-created_at'], name='core_auditl_action_d80c2d_idx'), models.Index(fields=['actor', '-created_at'], name='core_auditl_actor_i_502baf_idx')],
            },
        ),
    ]
