# Generated by Django 5.1.3 on 2026-09-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('register', 'Register'), ('password_changed', 'Password changed'), ('sub_activated', 'Subscription activated'), ('sub_cancelled', 'Subscription cancelled'), ('pay_succeeded', 'Payment succeeded'), ('pay_failed', 'Payment failed'), ('book_created', 'Booking created'), ('book_cancelled', 'Booking cancelled'), ('admin_user_toggled', 'Admin: user toggled'), ('admin_user_role_changed', 'Admin: role changed')], max_length=40),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=80)),
                ('first_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('membership', 'Memberships and pricing'), ('classes', 'Classes and schedule'), ('coaching', 'Personal coaching'), ('facilities', 'Facilities'), ('other', 'Something else')], default='other', max_length=20)),
                ('message', models.TextField(max_length=4000)),
                ('is_handled', models.BooleanField(default=False, help_text='Ticked by staff once the enquiry has been answered.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_handled', '-created_at'], name='core_contac_is_hand_c5c818_idx')],
            },
        ),
    ]
